frase = 'Curso em video Python'
dividido = frase.split()
print((frase[:2] + frase[5:14]).upper())
frase.upper()
print(frase.replace('Curso', 'Penis'))
frase = frase.upper()
print(frase)
frase = frase.capitalize()
print('Cu está presente na frase?.. {}'.format('Cu' in frase))
print(frase.find('em'))
print(dividido)