linha = input('Digite algo:.. ')
print('Qual o tipo do conteúdo digitado acima?.. {}'.format(type(linha)))
print('Só tem espaço?.. {}'.format(linha.isspace()))
print('É um número?.. {}'.format(linha.isnumeric()))
print('É alfabético?.. {}'.format(linha.isalpha()))
print('É alfanumérico?.. {}'.format(linha.isalnum()))
print('Está todo em maiúsculo?.. {}'.format(linha.isupper()))
print('Está todo em minúsculo?.. {}'.format(linha.islower()))
print('Está capitalizado?.. {}'.format(linha.istitle()))
